// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5ajWVWY0QqlnOSVLR_HZDTRp_2OMtmY',
    appId: '1:18861334187:web:464d7bb18434f91e1f21ee',
    messagingSenderId: '18861334187',
    projectId: 'watches-17aa7',
    authDomain: 'watches-17aa7.firebaseapp.com',
    storageBucket: 'watches-17aa7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Shl16GBYqAs9IqihLgsXmnhDbOtPpw8',
    appId: '1:18861334187:android:4e5a98685e579d2a1f21ee',
    messagingSenderId: '18861334187',
    projectId: 'watches-17aa7',
    storageBucket: 'watches-17aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PLtC--HGp9v2AUcTCg4YlS_4z6jy_ZA',
    appId: '1:18861334187:ios:5c130d7e50775fb81f21ee',
    messagingSenderId: '18861334187',
    projectId: 'watches-17aa7',
    storageBucket: 'watches-17aa7.appspot.com',
    iosBundleId: 'com.example.watchesHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9PLtC--HGp9v2AUcTCg4YlS_4z6jy_ZA',
    appId: '1:18861334187:ios:5c130d7e50775fb81f21ee',
    messagingSenderId: '18861334187',
    projectId: 'watches-17aa7',
    storageBucket: 'watches-17aa7.appspot.com',
    iosBundleId: 'com.example.watchesHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw5ajWVWY0QqlnOSVLR_HZDTRp_2OMtmY',
    appId: '1:18861334187:web:9b2e2c6ee6999ef01f21ee',
    messagingSenderId: '18861334187',
    projectId: 'watches-17aa7',
    authDomain: 'watches-17aa7.firebaseapp.com',
    storageBucket: 'watches-17aa7.appspot.com',
  );
}
